export const data = {
    title: "Shop By Category",
    image1: "src/assets/1.png",
    image2: "src/assets/2.png",
    image3: "src/assets/3.png",
    image4: "src/assets/4.png",
    image5: "src/assets/5.png",
    image6: "src/assets/6.png",
    image7: "src/assets/7.png",
    image8: "src/assets/8.png",
    image9: "src/assets/9.png",
    image10: "src/assets/10.png",
    image11: "src/assets/11.png",
    image12: "src/assets/12.png",
    image13: "src/assets/13.png",
    image14: "src/assets/14.png",
    image15: "src/assets/15.png",
    image16: "src/assets/16.png",
};
